contact_links:
  - name: Diddi and the Bugs usage guide
    url: https://github.com/DiddiLeija/diddi-and-the-bugs/blob/main/guide.md
    about: This guide may help you resolve doubts about using this game.
